#!/bin/bash
source ./../db.env

QUERY_FILE="$1"

sqlplus -s "$DB_USER/$DB_PASS@$DB_CONN" <<EOF
SET PAGESIZE 9999
SET LINESIZE 9999
SET FEEDBACK OFF
SET HEADING ON
SET MARKUP HTML ON TABLE "BORDER='1' CELLSPACING='0' CELLPADDING='6'"

@$QUERY_FILE

EXIT;
EOF
