DROP TABLE incident_reports CASCADE CONSTRAINTS;
DROP TABLE reports CASCADE CONSTRAINTS;
DROP TABLE incidents CASCADE CONSTRAINTS;
DROP TABLE staff CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE departments CASCADE CONSTRAINTS;
DROP TABLE contacts CASCADE CONSTRAINTS;
DROP TABLE organizations CASCADE CONSTRAINTS;